language: java
install: true

os: linux
dist: xenial

matrix:
  include:
    - jdk: openjdk10

script:
  - chmod +x gradlew
  - ./gradlew build

env:
  global:
    - secure: FxN828yydlJfl/6G8EtRxJ3lWAFvMgCiRmX5OpAaV9HVU6DZ8SbkLusN7pX9KBkOsUNZOfAF/iMV9rw/+PYKpeElz0v72nJLYv5diD/wyE5hVP8n95IUzBm3X+KR+gykacsJSGKLoPl1yfNnLidvELLEbiS3KkCOenIFfaa8gqzrqkvT3vlyJhuNa3JqQoDZ81XPzwzWhM0VyXN2/2CkcnjRTWroLmtHcLjYHHW7FwzWJXxMNsTqLJKXjf2bskb+8gDvQ1bcMUETYONdRktDNxgFflp5FWINmkbSvB4U8YZkroXgWAA7RiQcx8VChvFIbWeR17/SR0WFv8YojSqmiwUiKUIuFWDoXK3HslC0TLLjLGiXiyIKCyitfcowsKPY+AgPCtNSlqOvQjohLOR+JJ+epXYxtIobQQuJqkAFZmlO6C8wCjbwZzg3YUkhy2B796sNVqAEW4IqMfhs6Aqy60zez+ovCqmA0fhh516e7SmN3dR1vgxw4WTVm/btXZNy7ff9TqbXCX8h1UPN/AF2g6YsiG+usTANgBTTMead18A5pmx/5gUKH+eiTdrWnbQFzNUz8K3eATAfUwxcUxkHrWI7NaqMbrgLNkvdHZicavqzpO3Koh7aiyIt8+5QCMdyq/ff/YZZUOEqiPLpAu2vVfYtXBv1CZH3RgOMK6N0ilY=
    - secure: oUXfX0n6K3IuxPqMVCaFHFCESf9mpZLSzi1bn+h6GxP0ItmxH9f923gNqV2FT8OVQJlel09X4ssHKrUn11hUcWOwP/LRqgQ8u0wziE+gqWaE7NbbLSSkrFrL00BZHcnzulLO9Nk6b7H9KNuAssO+EuQXLL5yM+y4ICA+c60Ey1FH5aHMNE0107nV0oGXwasCdcGq4nOOUqy8Z7YQgJVkftlX0P2hOOg+52cWXqF7kb7PmYr7aHJ9tDfFLCPabje+SizgCHqIuqmRbEp2ATbeLPDn/JFVJBwB/bTUXd9lC+EToNKahKP+HwKxszpc7M19Ny2UVtywONJXxb5ifK4fyWSLKjO7g2pW25hr8jIBlYCQ2hJhCMmWXsPD0EkbgHKQmhesb+H92uUewsxvRlZR/DN1DAGblwp7yVIXwwMTgslj9tC2rRALEHfPPtMZRnNgPd0QhXSOopfN1aGjpYMgxf/xIB0oslxAN/IqS44K8HU97hyc8sXaGkIDBtoHeAC+xfd3DIklFASrm7KGpRTgthzIeQu9DRCqVJC9/0dLMX8aQm6Y7MasaD+5cpUMXiQK4QVvLA2dlqz3W6K99feavdTOa87d4Oj+gsfCSxsYETxRISFdDZ1X/9y7SqBg8B22GmokQokngqzDeDtOlTn40rYDLFditTe/FbQIhCwBDaQ=

# See https://guides.gradle.org/executing-gradle-builds-on-travisci/#enable_caching_of_downloaded_artifacts.
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
