# Check for dependency updates each week.

name: Check for Dependency Updates

on:
  schedule:
    - cron: 23 1 * * 0

jobs:
  check:
    runs-on: ubuntu-latest

    # Our global environment variables used as a replacement for providing an `oc_okapi.properties` file.
    env:
      OC_OKAPI_DE_CONSUMER_KEY: DUMMY
      OC_OKAPI_DE_CONSUMER_SECRET: DUMMY

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Use OpenJDK from https://jdk.java.net/.
      # See https://github.com/sormuras/download-jdk
      - name: Download JDK
        uses: sormuras/download-jdk@v1
        id: jdk
        with:
          feature: 14
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: ${{ steps.jdk.outputs.file }}
      - name: Display Java Version
        run: java --version

      # Cache some Gradle files.
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Run the actual steps after the preparations.
      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew
      - name: Clean Build Area
        run: ./gradlew clean
      - name: Check for Updates
        run: ./gradlew dependencyUpdates

      # Clean some files before caching.
      - name: Cache Cleanup
        run: |
          rm -f  ~/.gradle/caches/modules-2/modules-2.lock
          rm -fr ~/.gradle/caches/*/plugin-resolution/
